package com.scalable.diff.restcompare.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * The persistent class for the TJSON_BINARY_DATA database table.
 * 
 * @author Sasank Samudrala
 * @version 0.0.1
 */
@Entity
@Table(name="TJSON_BINARY_DATA")
public class JsonBinaryDataEntity {
    

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long autogeneratedId;
    
    //@NaturalId (mutable = false)
    @NotNull
    private Integer inputId;
    
    @NotNull
    private String encodedValue;
    
    @NotNull
    private String direction;
    
    
    public JsonBinaryDataEntity() {
        super();
    }

    public JsonBinaryDataEntity(Integer inputId, String encodedValue, String direction) {
        super();
        this.inputId = inputId;
        this.encodedValue = encodedValue;
        this.direction = direction;
    }
    

    public Integer getInputId() {
        return inputId;
    }

    public void setInputId(Integer inputId) {
        this.inputId = inputId;
    }

    public String getEncodedValue() {
        return encodedValue;
    }

    public void setEncodedValue(String encodedValue) {
        this.encodedValue = encodedValue;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }
    

    
}
